version: '3'

services:
  # Infra
  api-gateway:
    image: nginx
    volumes:
      - ./infra/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 8881:8881
      - 8882:8882
    depends_on:
      - requests
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,owner=ruan,environment=development
    networks:
      - app-network
  loki:
    image: grafana/loki:2.1.0
    volumes:
      - ./infra/loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    networks:
      - app-network
    depends_on:
      - minio
  grafana:
    image: grafana/grafana:7.3.7
    restart: unless-stopped
    volumes:
      - ./infra/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./data/grafana:/var/lib/grafana
    networks:
      - app-network
    depends_on:
      - loki
  minio:
    # port 9000

    image: minio/minio:RELEASE.2022-03-11T23-57-45Z
    restart: unless-stopped
    entrypoint: [ "" ]
    command:
      [
        "sh",
        "-c",
        "mkdir -p /export/loki && minio server /export"
      ]
    environment:
      - MINIO_ACCESS_KEY=697d0993dd097f38d5b8
      - MINIO_SECRET_KEY=9f88738761b57c63f6a81bdfd471
    volumes:
      - ./data/minio:/export
    ports:
      - 9000:9000
    networks:
      - app-network

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongo_storage:/data/db
    networks:
      - app-network
    depends_on:
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,owner=ruan,environment=development
    # Serverless Functions
  requests:
    build:
      context: .
      dockerfile: ./functions/requests/Dockerfile
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044

    depends_on:
      - db
      - loki

    networks:
      - app-network

networks:
  app-network:


volumes:
  minio_data: {}
  loki_data: {}
  grafana_data: {}
  data: {}
  mongo_storage: {}
