version: '3.7'

services:
  certbot:
    image: certbot/certbot
    command: certonly --standalone --preferred-challenges http --agree-tos --email ${EMAIL} -d ${DOMAIN}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
