version: '3.7'

name: tracking-detector

services:
  # Infra
  api-gateway:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    volumes:
      - ./infra/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mongo-express
      - export
      - minio
      - grafana
      - requests
      - loki
    networks:
      - app-network
  loki:
    restart: unless-stopped
    image: grafana/loki:2.6.1
    volumes:
      - loki_data:/loki
      - ./infra/loki/loki.yaml:/etc/loki/loki-config.yaml
    networks:
      - app-network
  promtail:
    restart: unless-stopped
    image: grafana/promtail:2.6.1
    volumes:
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - app-network
  grafana:
    restart: unless-stopped
    image: grafana/grafana:9.2.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./infra/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - app-network
    depends_on:
      - loki
  minio:
    restart: unless-stopped
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address ":9001" /data
    networks:
      - app-network
  mongo-express:
    restart: unless-stopped
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017/tracking-detector
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_SITE_BASEURL=/mongo
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo:latest
    restart: unless-stopped
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=tracking-detector
    volumes:
      - mongo_storage:/data/db
    networks:
      - app-network
    depends_on:
      - loki
    # Serverless Functions
  requests:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./go/functions/requests/Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_PRIVATE_KEY=adminadmin
      - EXPORT_BUCKET_NAME=exports
      - MINIO_URI=minio:9000
    depends_on:
      - minio
      - db
      - loki
    networks:
      - app-network
  export:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./go/functions/export/Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_PRIVATE_KEY=adminadmin
      - EXPORT_BUCKET_NAME=exports
      - MINIO_URI=minio:9000
    depends_on:
      - minio
      - db
      - loki
    networks:
      - app-network
  download:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./go/functions/download/Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_PRIVATE_KEY=adminadmin
      - MODEL_BUCKET_NAME=models
      - EXPORT_BUCKET_NAME=exports
      - MINIO_URI=minio:9000
    depends_on:
      - minio
      - db
      - loki
    networks:
      - app-network
  training:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./python/Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_PRIVATE_KEY=adminadmin
      - EXPORT_BUCKET_NAME=exports
      - MODEL_BUCKET_NAME=models
      - MINIO_URI=minio:9000
    depends_on:
      - minio
      - db
      - loki
    networks:
      - app-network
  training-runs:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./go/functions/training-runs/Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/tracking-detector
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_PRIVATE_KEY=adminadmin
      - MODEL_BUCKET_NAME=models
      - EXPORT_BUCKET_NAME=exports
      - MINIO_URI=minio:9000
    depends_on:
      - minio
      - db
      - loki
    networks:
      - app-network

networks:
  app-network:


volumes:
  minio_data: {}
  loki_data: {}
  grafana_data: {}
  data: {}
  mongo_storage: {}
