# https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencies-setup
auth_enabled: false

server:
  http_listen_port: 3100
ingester:
  lifecycler:
    clean_stale: true
    num_workers: 1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 8h