apiVersion: 1

deleteDatasources:
  - name: loki

datasources:
  - name: loki
    type: loki
    url: http://loki:3100
    orgId: 1
    basicAuth: false
    isDefault: true
    version: 1
    editable: false